### ISSUE TITLE
Requête 

### ISSUE THREAD

**Issue by fabius32** [Le-foucheur/Typst-VarTable#6]
Bonjour,
J’utilise depuis peu typst et votre package pour les tableaux de variations. 

Est ce que vous pourriez dans une mise donner la possibilité de faire des pointillés à l’intérieur du tableau à la place de traits pleins. Notamment pour les zeros du tableau de signes. 

Merci.

**Comment by Le-foucheur** [comment]
bonjours, déjà merci du retour

Et oui il est tout a faits possible de rajouter les pointier voir plus, j'essayerais de le faire durant la semaine mais je garantie rien

**Comment by Le-foucheur** [comment]
La maj viens de tomber ce lundi ou mardi, normalement tout est bon pour les pointillés et même plus !
