### ISSUE TITLE
Dimensions paramétrables

### ISSUE THREAD

**Issue by Akilon27** [Le-foucheur/Typst-VarTable#8]
Bonjour,
Merci de la réponse rapide à ma requête précédente. Je viens de voir dans l'autre requête fermée que vous parlez français.
Merci surtout pour ce package très utile !

Est-il possible de rendre certaines dimensions paramétrables comme dans tkz-tab ?
Je pense aux hauteurs des différentes lignes, à la largeur de la première colonne puis entre les différentes valeurs.

Merci d'avance

Remarques : dans les commentaires présents sur le fichier tabvar.typ : il n'y a pas que l'épaisseur et la couleur des traits que l'on peut changer et si line-0:true alors mark-line influence les 0 mais plus les autres.

**Comment by Le-foucheur** [comment]
tkz-tab c'est l'extension pour latex ? 
Mais dans tout les cas faudrais que je m'en inspire, mais pour l'heure c'est assez compliqué pour bosser sérieusement sur un projet à cause des études 
Mais une fois que j'en sort, je pense que je vais tout revoir de 0 car la mon code est assez moche et je me baserais directement sur Cetz, ça seras plus simple 
Donc pour toutes les modifs assez complexe (pour moi) à implanté on va attendre encore quelques que année mais ça devrais ce faire !

Mais merci du retour, je prend note

**Comment by Akilon27** [comment]
Oui, c'est l'extension LaTeX. Merci pour tout le travail effectué, la version actuelle est déjà largement utilisable.
Bon courage pour la fin des études.
